# Generated by Django 4.0.3 on 2022-04-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('url', models.URLField(db_column='url')),
                ('date_of_publication', models.DateTimeField(db_column='date_of_publication')),
                ('headline', models.CharField(db_column='headline', max_length=100)),
                ('main_text', models.TextField(db_column='main_text')),
            ],
        ),
        migrations.CreateModel(
            name='Lanes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('green', models.TextField(db_column='green', null=True)),
                ('yellow', models.TextField(db_column='yellow', null=True)),
                ('red', models.TextField(db_column='red', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, db_column='country', max_length=50)),
                ('location', models.CharField(blank=True, db_column='location', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('open_status', models.TextField(db_column='open_status', null=True)),
                ('quarantine_days', models.TextField(db_column='quarantine_days', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, db_column='country', max_length=50)),
                ('new_cases', models.CharField(db_column='new_cases', max_length=50, null=True)),
                ('active_cases', models.CharField(db_column='active_cases', max_length=50, null=True)),
                ('new_percentage', models.CharField(db_column='new_percentage', max_length=50, null=True)),
                ('active_percentage', models.CharField(db_column='active_percentage', max_length=50, null=True)),
                ('can_you_enter', models.TextField(db_column='can_you_enter', null=True)),
                ('lanes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.lanes')),
                ('overview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.overview')),
            ],
        ),
        migrations.CreateModel(
            name='WhatToExpect',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('before_your_trip', models.TextField(db_column='before_your_trip', null=True)),
                ('on_arrival', models.TextField(db_column='on_arrival', null=True)),
                ('quarantine_details', models.TextField(db_column='quarantine_details', null=True)),
                ('travel_restrictions', models.TextField(db_column='travel_restrictions', null=True)),
                ('travel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scraper.travelinfo')),
            ],
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='what_to_expect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.whattoexpect'),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField(blank=True, db_column='event_date', null=True)),
                ('diseases', models.CharField(blank=True, db_column='diseases', max_length=50, null=True)),
                ('syndromes', models.CharField(blank=True, db_column='syndromes', max_length=50, null=True)),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.locations')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.articles')),
            ],
        ),
        migrations.AddField(
            model_name='overview',
            name='travel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scraper.travelinfo'),
        ),
        migrations.AddField(
            model_name='lanes',
            name='travel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scraper.travelinfo'),
        ),
    ]
