# Generated by Django 4.0.3 on 2022-03-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('url', models.URLField(db_column='url')),
                ('date_of_publication', models.DateTimeField(db_column='date_of_publication')),
                ('headline', models.CharField(db_column='headline', max_length=100)),
                ('main_text', models.TextField(db_column='main_text')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('country', models.CharField(db_column='country', max_length=50)),
                ('location', models.CharField(db_column='location', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField(db_column='event_date')),
                ('diseases', models.CharField(db_column='diseases', max_length=50)),
                ('syndromes', models.CharField(db_column='syndromes', max_length=50)),
                ('locations', models.ManyToManyField(to='scraper.locations')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.articles')),
            ],
        ),
    ]
