# Generated by Django 4.0.3 on 2022-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(blank=True, db_column='country', max_length=50),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(blank=True, db_column='location', max_length=50),
        ),
        migrations.AlterField(
            model_name='reports',
            name='diseases',
            field=models.CharField(blank=True, db_column='diseases', max_length=50),
        ),
        migrations.AlterField(
            model_name='reports',
            name='event_date',
            field=models.DateTimeField(blank=True, db_column='event_date'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='locations',
            field=models.ManyToManyField(blank=True, to='scraper.locations'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='syndromes',
            field=models.CharField(blank=True, db_column='syndromes', max_length=50),
        ),
    ]
