# Generated by Django 4.0.3 on 2022-03-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_reports_locations_reports_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='diseases',
            field=models.CharField(blank=True, db_column='diseases', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='syndromes',
            field=models.CharField(blank=True, db_column='syndromes', max_length=50, null=True),
        ),
    ]
