# Generated by Django 4.0.4 on 2022-04-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_reports_diseases_alter_reports_syndromes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, db_column='country', max_length=50)),
                ('new_cases', models.IntegerField(db_column='new_cases', null=True)),
                ('active_cases', models.IntegerField(db_column='active_cases', null=True)),
                ('new_percentage', models.DecimalField(db_column='new_percentage', decimal_places=2, max_digits=2)),
                ('active_percentage', models.DecimalField(db_column='active_percentage', decimal_places=2, max_digits=2)),
                ('can_you_enter', models.TextField(db_column='can_you_enter', null=True)),
                ('what_to_expect', models.TextField(db_column='what_to_expect', null=True)),
            ],
        ),
    ]
