# Generated by Django 4.0.4 on 2022-04-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_travelinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.TextField(db_column='green', null=True)),
                ('yellow', models.TextField(db_column='yellow', null=True)),
                ('red', models.TextField(db_column='red', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatToExpect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_your_trip', models.TextField(db_column='before_your_trip', null=True)),
                ('on_arrival', models.TextField(db_column='on_arrival', null=True)),
                ('quarantine_details', models.TextField(db_column='quarantine_details', null=True)),
                ('travel_restrictions', models.TextField(db_column='travel_restrictions', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='lanes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.lanes'),
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='what_to_expect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.whattoexpect'),
        ),
    ]
